### ISSUE TITLE
Will the tool still work if we upgrade this to ^10?

### ISSUE THREAD

**Issue by alibkaba** [laravel/forge-monitor#73]
https://github.com/laravel/forge-monitor/blob/adba0ff5d5f53acba5cbe89925c72742c64ea6ab/composer.json#L16C1-L17C1

**Comment by jbrooksuk** [comment]
I'm not sure off the top of my head, sorry! We don't have any plans to update this tool just yet, since Forge will orchestrate all of the PHP version requirements anyway.

**Comment by alibkaba** [comment]
After some digging, I found that this Forge Monitor tool is essentially a feature included in the business plan, but enhanced.

https://forge.laravel.com/features/server-monitoring
